# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: entity.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65ntity.proto\"G\n\rEntityRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x10\n\x08\x64ocument\x18\x02 \x01(\t\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"<\n\x0c\x45ntityRecord\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x0e\n\x06\x65ntity\x18\x03 \x01(\t\"1\n\x0e\x45ntityResponse\x12\x1f\n\x08\x65records\x18\x01 \x03(\x0b\x32\r.EntityRecord26\n\x08\x45ntities\x12*\n\x07\x65xtract\x12\x0e.EntityRequest\x1a\x0f.EntityResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'entity_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ENTITYREQUEST._serialized_start=16
  _ENTITYREQUEST._serialized_end=87
  _ENTITYRECORD._serialized_start=89
  _ENTITYRECORD._serialized_end=149
  _ENTITYRESPONSE._serialized_start=151
  _ENTITYRESPONSE._serialized_end=200
  _ENTITIES._serialized_start=202
  _ENTITIES._serialized_end=256
# @@protoc_insertion_point(module_scope)
